/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    utilisateurs: UtilisateurAuthOperations;
  };
  blocks: {};
  collections: {
    specialisations: Specialisation;
    programmes: Programme;
    sessions: Session;
    articles: Article;
    temoignages: Temoignage;
    partenaires: Partenaire;
    pages: Page;
    medias: Media;
    'demandes-rappel': DemandesRappel;
    utilisateurs: Utilisateur;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    specialisations: SpecialisationsSelect<false> | SpecialisationsSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    temoignages: TemoignagesSelect<false> | TemoignagesSelect<true>;
    partenaires: PartenairesSelect<false> | PartenairesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    medias: MediasSelect<false> | MediasSelect<true>;
    'demandes-rappel': DemandesRappelSelect<false> | DemandesRappelSelect<true>;
    utilisateurs: UtilisateursSelect<false> | UtilisateursSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Utilisateur;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UtilisateurAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Les filières métier qui regroupent les formations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialisations".
 */
export interface Specialisation {
  id: number;
  nom?: string | null;
  /**
   * Apparaît dans l'adresse : /specialisations/finance-comptabilite
   */
  slug: string;
  /**
   * Une phrase courte, affichée sur les cartes et en titre de section.
   */
  accroche?: string | null;
  description?: string | null;
  debouches?:
    | {
        titre?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Les formations du catalogue. Les dates se gèrent dans « Sessions ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  titre?: string | null;
  /**
   * Apparaît dans l'adresse : /formations/preparation-certification-pmp
   */
  slug: string;
  specialisation: number | Specialisation;
  type: 'certification' | 'parcours-executif' | 'metier' | 'sur-mesure';
  niveau: 'debutant' | 'intermediaire' | 'avance';
  /**
   * Deux ou trois lignes, affichées sous le titre.
   */
  accroche?: string | null;
  objectifs?: string | null;
  /**
   * À laisser vide si la formation ne prépare pas à une certification.
   */
  certification?: string | null;
  dureeHeures: number;
  rythme?: string | null;
  langue: string;
  publicVise?:
    | {
        valeur?: string | null;
        id?: string | null;
      }[]
    | null;
  competences?:
    | {
        valeur?: string | null;
        id?: string | null;
      }[]
    | null;
  prerequis?: string | null;
  /**
   * Ce que le participant emporte : support, replays, corrigés, grilles de lecture.
   */
  livrables?:
    | {
        valeur?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ressources fournies en plus du cours : templates Excel, Word, PowerPoint, cas fil rouge.
   */
  outils?:
    | {
        valeur?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mention imposée par un tiers, affichée sous la fiche. Exemple : PMP® est une marque du Project Management Institute ; les frais d'examen ne sont pas inclus.
   */
  mentionsLegales?: string | null;
  debouches?:
    | {
        valeur?: string | null;
        id?: string | null;
      }[]
    | null;
  modules?:
    | {
        titre?: string | null;
        lecons?:
          | {
              titre?: string | null;
              dureeMinutes: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Les dates ouvertes à la réservation. Une ligne par ville et par période.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  /**
   * Composé automatiquement à l'enregistrement.
   */
  reference?: string | null;
  programme: number | Programme;
  /**
   * « En ligne » est réservé au e-learning, qui n'est pas ouvert cette année. Ne pas l'utiliser.
   */
  mode: 'presentiel' | 'visio' | 'en-ligne';
  ville?: string | null;
  pays?: string | null;
  /**
   * À laisser vide : le lien Google Meet sera créé automatiquement à l'ouverture de la session (phase 02).
   */
  lienVisio?: string | null;
  debut: string;
  fin: string;
  /**
   * Les fiches annoncent leurs horaires en UTC. Sans cette précision, un participant à Abidjan et un autre à Casablanca ne lisent pas la même heure.
   */
  fuseau?: ('UTC' | 'GMT' | 'Africa/Casablanca' | 'Africa/Abidjan' | 'Africa/Dakar') | null;
  /**
   * Texte libre montré sous les dates sur la fiche formation.
   */
  cadence?: string | null;
  capacite: number;
  /**
   * Saisie à la main en V1. À partir de la phase 02, ce compteur sera tenu par les réservations payées.
   */
  placesReservees: number;
  /**
   * En unité entière — saisir 1250 pour 1 250 €. La conversion en centimes se fait côté application.
   */
  prix: number;
  devise: 'EUR' | 'MAD' | 'XOF';
  updatedAt: string;
  createdAt: string;
}
/**
 * Les articles du blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  titre?: string | null;
  /**
   * Apparaît dans l'adresse : /blog/mon-article
   */
  slug: string;
  categorie: 'certifications' | 'finance' | 'management' | 'carriere' | 'institut';
  publieLe: string;
  auteur: string;
  /**
   * Environ 200 mots par minute.
   */
  lectureMinutes: number;
  /**
   * Affichée en encadré à la fin de l'article. C'est ce qui transforme une lecture en demande de renseignement.
   */
  programmeLie?: (number | null) | Programme;
  /**
   * Reprise sur les cartes du blog et dans les partages WhatsApp.
   */
  couverture?: (number | null) | Media;
  /**
   * Deux ou trois lignes, reprises sur les cartes et dans les partages.
   */
  chapo?: string | null;
  contenu?:
    | (
        | {
            texte: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraphe';
          }
        | {
            texte: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intertitre';
          }
        | {
            items?:
              | {
                  valeur: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'liste';
          }
        | {
            texte: string;
            auteur: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'citation';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images du site. Le texte alternatif est obligatoire.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medias".
 */
export interface Media {
  id: number;
  /**
   * Ce que dirait quelqu'un qui décrit l'image à une personne qui ne la voit pas. « Logo EC-Council », pas « image1 ».
   */
  alt: string;
  /**
   * À renseigner pour toute image dont CLIXA n'est pas l'auteur.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    vignette?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    carte?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Paroles d'anciens participants.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages".
 */
export interface Temoignage {
  id: number;
  /**
   * Deux à quatre lignes. Au-delà, personne ne lit.
   */
  texte?: string | null;
  auteur: string;
  fonction?: string | null;
  programme?: (number | null) | Programme;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Référentiels et standards visés par les parcours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partenaires".
 */
export interface Partenaire {
  id: number;
  nom: string;
  nature: 'referentiel' | 'certificateur' | 'institution';
  /**
   * Facultatif. Le site affiche le nom en toutes lettres si aucun logo n'est fourni.
   */
  logo?: (number | null) | Media;
  lien?: string | null;
  /**
   * Le plus petit apparaît en premier.
   */
  ordre: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Pages de texte : mentions légales, confidentialité, CGV. Ne publier qu'après relecture juridique.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  titre?: string | null;
  /**
   * Apparaît dans l'adresse : /mentions-legales
   */
  slug: string;
  /**
   * Affichée en haut de page — attendu sur un document juridique.
   */
  miseAJour?: string | null;
  contenu?:
    | (
        | {
            texte: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraphe';
          }
        | {
            texte: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intertitre';
          }
        | {
            items?:
              | {
                  valeur: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'liste';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Les demandes déposées depuis le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demandes-rappel".
 */
export interface DemandesRappel {
  id: number;
  nom: string;
  email: string;
  whatsapp: string;
  pays: string;
  /**
   * Vide si la personne ne savait pas encore.
   */
  programme?: (number | null) | Programme;
  message?: string | null;
  statut: 'nouvelle' | 'rappelee' | 'devis' | 'inscrite' | 'sans-suite';
  /**
   * Jamais affichées au visiteur.
   */
  notes?: string | null;
  /**
   * D'où venait la personne au moment de la demande.
   */
  origine?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utilisateurs".
 */
export interface Utilisateur {
  id: number;
  nom: string;
  /**
   * Direction : accès complet. Pédagogie : catalogue et sessions. Rédaction : blog et pages.
   */
  role: 'direction' | 'pedagogie' | 'redaction';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'utilisateurs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'specialisations';
        value: number | Specialisation;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'temoignages';
        value: number | Temoignage;
      } | null)
    | ({
        relationTo: 'partenaires';
        value: number | Partenaire;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'medias';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'demandes-rappel';
        value: number | DemandesRappel;
      } | null)
    | ({
        relationTo: 'utilisateurs';
        value: number | Utilisateur;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'utilisateurs';
    value: number | Utilisateur;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'utilisateurs';
    value: number | Utilisateur;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialisations_select".
 */
export interface SpecialisationsSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  accroche?: T;
  description?: T;
  debouches?:
    | T
    | {
        titre?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  specialisation?: T;
  type?: T;
  niveau?: T;
  accroche?: T;
  objectifs?: T;
  certification?: T;
  dureeHeures?: T;
  rythme?: T;
  langue?: T;
  publicVise?:
    | T
    | {
        valeur?: T;
        id?: T;
      };
  competences?:
    | T
    | {
        valeur?: T;
        id?: T;
      };
  prerequis?: T;
  livrables?:
    | T
    | {
        valeur?: T;
        id?: T;
      };
  outils?:
    | T
    | {
        valeur?: T;
        id?: T;
      };
  mentionsLegales?: T;
  debouches?:
    | T
    | {
        valeur?: T;
        id?: T;
      };
  modules?:
    | T
    | {
        titre?: T;
        lecons?:
          | T
          | {
              titre?: T;
              dureeMinutes?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  reference?: T;
  programme?: T;
  mode?: T;
  ville?: T;
  pays?: T;
  lienVisio?: T;
  debut?: T;
  fin?: T;
  fuseau?: T;
  cadence?: T;
  capacite?: T;
  placesReservees?: T;
  prix?: T;
  devise?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  categorie?: T;
  publieLe?: T;
  auteur?: T;
  lectureMinutes?: T;
  programmeLie?: T;
  couverture?: T;
  chapo?: T;
  contenu?:
    | T
    | {
        paragraphe?:
          | T
          | {
              texte?: T;
              id?: T;
              blockName?: T;
            };
        intertitre?:
          | T
          | {
              texte?: T;
              id?: T;
              blockName?: T;
            };
        liste?:
          | T
          | {
              items?:
                | T
                | {
                    valeur?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        citation?:
          | T
          | {
              texte?: T;
              auteur?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages_select".
 */
export interface TemoignagesSelect<T extends boolean = true> {
  texte?: T;
  auteur?: T;
  fonction?: T;
  programme?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partenaires_select".
 */
export interface PartenairesSelect<T extends boolean = true> {
  nom?: T;
  nature?: T;
  logo?: T;
  lien?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  miseAJour?: T;
  contenu?:
    | T
    | {
        paragraphe?:
          | T
          | {
              texte?: T;
              id?: T;
              blockName?: T;
            };
        intertitre?:
          | T
          | {
              texte?: T;
              id?: T;
              blockName?: T;
            };
        liste?:
          | T
          | {
              items?:
                | T
                | {
                    valeur?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medias_select".
 */
export interface MediasSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        vignette?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        carte?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demandes-rappel_select".
 */
export interface DemandesRappelSelect<T extends boolean = true> {
  nom?: T;
  email?: T;
  whatsapp?: T;
  pays?: T;
  programme?: T;
  message?: T;
  statut?: T;
  notes?: T;
  origine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utilisateurs_select".
 */
export interface UtilisateursSelect<T extends boolean = true> {
  nom?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}